// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTFCU5aD6azPMk5-wE29ixOogUbBpafpA',
    appId: '1:333396433158:web:987ebfea094bd802382687',
    messagingSenderId: '333396433158',
    projectId: 'oficina-148c8',
    authDomain: 'oficina-148c8.firebaseapp.com',
    storageBucket: 'oficina-148c8.firebasestorage.app',
    measurementId: 'G-5XJRJF1B6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNEgxsejq1jzBnbjCxFxt9OF0Rv5bqMHU',
    appId: '1:333396433158:android:1d32bf514951a3b0382687',
    messagingSenderId: '333396433158',
    projectId: 'oficina-148c8',
    storageBucket: 'oficina-148c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMCcBNA01-iFBQxt3C2k0IVcnRKa9ERbw',
    appId: '1:333396433158:ios:2a42de87070df425382687',
    messagingSenderId: '333396433158',
    projectId: 'oficina-148c8',
    storageBucket: 'oficina-148c8.firebasestorage.app',
    iosBundleId: 'com.example.appOficina',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMCcBNA01-iFBQxt3C2k0IVcnRKa9ERbw',
    appId: '1:333396433158:ios:2a42de87070df425382687',
    messagingSenderId: '333396433158',
    projectId: 'oficina-148c8',
    storageBucket: 'oficina-148c8.firebasestorage.app',
    iosBundleId: 'com.example.appOficina',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTFCU5aD6azPMk5-wE29ixOogUbBpafpA',
    appId: '1:333396433158:web:a03f31da69587afe382687',
    messagingSenderId: '333396433158',
    projectId: 'oficina-148c8',
    authDomain: 'oficina-148c8.firebaseapp.com',
    storageBucket: 'oficina-148c8.firebasestorage.app',
    measurementId: 'G-P32QY81NFB',
  );
}
